apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-bank-web
spec:
  template:
    spec:
      containers:
        - name: simple-bank-web
          volumeMounts:
            - mountPath: /etc/nginx/ssl/
              name: nginx-ssl-volume
            - mountPath: /etc/nginx/conf.d/
              name: nginx-conf
