services:

  bank:
    build:
      context: .
      dockerfile: Dockerfile
      # 环境变量: 与Dockerfile中的ARG字段相同
      args:
        # 后端应用版本
        VERSION: dev
        # 构建的镜像名称(用户名/容器名)
        REPOSITORY: "lisa/backend"
        # 本地开发机的系统
        GOOS: darwin
        # 本地开发机的架构
        GOARCH: arm64
        # 后端端口
        PORT: 8080
    image: lisa/backend:dev
    # 把<appname> 替换为go mod xxx生成的名称, 也就是go build 之后的应用名称, 例如backend
    container_name: simple-bank
    # 重启策略, 遇到错误就停止
    restart: unless-stopped
    environment:
      - GIN_MODE=release
      - DB_SOURCE="postgresql://postgres:postgres@localhost:5432/simple_bank?sslmode=disable"
    # 端口, 对应你的服务的端口
    ports:
      - "8080:8080"
    volumes:
      - ./app.env:/bin/app.env
      #      - # 初始化数据库
      #        init_database.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    command:
      - "/bin/main"

  postgres17:
    image: postgres:17.0-alpine3.20
    ports:
      - "5432:5432"
    container_name: postgres17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=simple_bank
