services:

  bank:
    build:
      context: .
      dockerfile: Dockerfile
    image: ccr.ccs.tencentyun.com/lisa/backend:v2.0.0
    # 把<appname> 替换为go mod xxx生成的名称, 也就是go build 之后的应用名称, 例如backend
    container_name: simple-bank
    # 重启策略, 遇到错误就停止
    restart: unless-stopped
    environment:
      - GIN_MODE=release
      - DB_SOURCE="postgresql://postgres:postgres@localhost:5432/simple_bank?sslmode=disable"
    # 端口, 对应你的服务的端口
    ports:
      - "0.0.0.0:30001:30001"
      - "0.0.0.0:30002:30002"
    volumes:
      - ./app.env:/bin/app.env
    command:
      - "/bin/main"
