services:
  postgres17:
    image: postgres:17.0-alpine3.20
    ports:
      - "5432:5432"
    container_name: postgres17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=simple_bank

  redis7:
    image: redis:7.4.1-alpine
    container_name: redis7
    ports:
      - "6379:6379"

