# https://hubgw.docker.com/_/postgres
services:
  db:
    container_name: postgres15
    restart: always
    # 使用 docker-compose 时设置共享内存限制
    shm_size: 512mb
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      # 数据库用户名
      POSTGRES_USER: postgres
      # 数据库用户密码
      POSTGRES_PASSWORD: postgres
      # 此可选环境变量可用于为首次启动映像时创建的默认数据库定义不同的名称。如果未指定，则将使用 POSTGRES_USER 的值。
      POSTGRES_DB: postgres

    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
