apiVersion: v1
kind: Service
metadata:
  name: swagger-simple-bank-service
spec:
  selector:
    app: simple-bank-swagger
  ports:
    - name: tcp
      port: 8080
      nodePort: 30005
      protocol: TCP
      targetPort: 8080
  type: NodePort

