# 参数: https://higress.cn/docs/latest/user/configmap/
# 全局TLS配置
apiVersion: v1
kind: ConfigMap
metadata:
  name: higress-https
  namespace: higress-system
data:
  cert: |
    automaticHttps: true
    # 证书过期前多少天自动Renew， 最大值为90天
    renewBeforeDays: 30
    fallbackForInvalidSecret: true
    acmeIssuer:
    - name: letsencrypt
      email: xicony@qq.com
    credentialConfig:
    - tlsIssuer: letsencrypt
      domains:
      - api.lookeke.com
      - web.lookeke.com
      tlsSecret: api-lookeke-com-secret
