apiVersion: v1
kind: Service
metadata:
  name: api-simple-bank-service
spec:
  selector:
    app: simple-bank-api
  ports:
    - name: tcp
      port: 8080
      nodePort: 30001
      protocol: TCP
      targetPort: 8080
  type: NodePort

