// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: entries.sql

package db

import (
	"context"
)

const CreateEntry = `-- name: CreateEntry :one
INSERT INTO entries(account_id, amount)
VALUES ($1, $2)
RETURNING id, account_id, amount, created_at
`

type CreateEntryParams struct {
	AccountID int64 `json:"accountID"`
	Amount    int64 `json:"amount"`
}

// CreateEntry
//
//	INSERT INTO entries(account_id, amount)
//	VALUES ($1, $2)
//	RETURNING id, account_id, amount, created_at
func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (Entries, error) {
	row := q.db.QueryRow(ctx, CreateEntry, arg.AccountID, arg.Amount)
	var i Entries
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const GetEntry = `-- name: GetEntry :one
SELECT id, account_id, amount, created_at
FROM entries
WHERE id = $1
LIMIT 1
`

// GetEntry
//
//	SELECT id, account_id, amount, created_at
//	FROM entries
//	WHERE id = $1
//	LIMIT 1
func (q *Queries) GetEntry(ctx context.Context, id int64) (Entries, error) {
	row := q.db.QueryRow(ctx, GetEntry, id)
	var i Entries
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const ListEntry = `-- name: ListEntry :many
SELECT id, account_id, amount, created_at
FROM entries
WHERE account_id = $1
ORDER BY id
LIMIT $2 OFFSET $3
`

type ListEntryParams struct {
	AccountID int64 `json:"accountID"`
	Limit     int64 `json:"limit"`
	Offset    int64 `json:"offset"`
}

// ListEntry
//
//	SELECT id, account_id, amount, created_at
//	FROM entries
//	WHERE account_id = $1
//	ORDER BY id
//	LIMIT $2 OFFSET $3
func (q *Queries) ListEntry(ctx context.Context, arg ListEntryParams) ([]Entries, error) {
	rows, err := q.db.Query(ctx, ListEntry, arg.AccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Entries{}
	for rows.Next() {
		var i Entries
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
