# 分配角色给 frontend-group 前端组 和 backend-group 后端组
# 并具有适当的权限
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.csv: |
    p, role:admin, applications, *, *, allow
    p, role:admin, applications, *, *, allow
    g, admin, role:admin
    g, admin, proj:bank:admin
# kubectl apply -f argocd-rbac-cm -n argocd
