# 存储TLS证书和密钥
apiVersion: v1
kind: Secret
metadata:
  name: nginx-ssl
  namespace: frontend
type: kubernetes.io/tls
data:
  tls.crt: base64编码的证书数据
  tls.key: base64编码的密钥数据
# kubectl create secret tls domain --cert  tls.crt --key tls.key -n frontend
