apiVersion: v1
kind: Service
metadata:
  name: web-simple-bank-service
spec:
  selector:
    app: simple-bank-web
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 30003
    - name: https
      protocol: TCP
      port: 443
      targetPort: 30004
    - name: quic
      protocol: UDP
      port: 443
      targetPort: 30004
  type: NodePort

