apiVersion: v1
kind: Service
metadata:
  name: web-simple-bank-service
spec:
  selector:
    app: simple-bank-web
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
      nodePort: 30003
    - name: https
      port: 4430
      targetPort: 4430
      protocol: TCP
      nodePort: 30004
    - name: quic
      port: 4430
      targetPort: 4430
      protocol: UDP
      nodePort: 30005
  type: NodePort
