apiVersion: v1
kind: Service
metadata:
  name: web-simple-bank-service
spec:
  selector:
    app: simple-bank-web
  ports:
    - protocol: TCP
      port: 443
      targetPort: 30004
  type: NodePort

